# name: Deploy to Amazon ECS

# on:
#   push:
#     branches: [ "dev" ]

# env:
#   AWS_REGION: us-east-1
#   ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
#   ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
#   ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
#   ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
#   ECR_IMAGE: ${{ secrets.ECR_IMAGE }}

#   CONTAINER_NAME: fastapi

# permissions:
#   contents: read

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     environment: production

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

#     - name: Retrieve most recent ECS task definition JSON file
#       id: retrieve-task-def
#       run: |
#         aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION --query taskDefinition > task-definition.json
#         echo "::set-output name=task-def-file::task-definition.json"

#     - name: Fill in the new image ID in the Amazon ECS task definition
#       id: task-def
#       uses: aws-actions/amazon-ecs-render-task-definition@v1
#       with:
#         task-definition: ${{ steps.retrieve-task-def.outputs.task-def-file }}
#         container-name: ${{ env.CONTAINER_NAME }}
#         image: ${{ env.ECR_IMAGE }}

#     - name: Deploy Amazon ECS task definition
#       uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#       with:
#         task-definition: ${{ steps.task-def.outputs.task-definition }}
#         service: ${{ env.ECS_SERVICE }}
#         cluster: ${{ env.ECS_CLUSTER }}
#         wait-for-service-stability: true
