name: Deploy to Amazon EC2

on:
  push:
    branches: [ "dev" ]

env:
  AWS_REGION: us-east-1
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_PORT: 22
  EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
  ECR_IMAGE_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: smki/capstone-2025-api
  ECR_IMAGE_TAG: ${{ secrets.ECR_IMAGE }}
  API_SERVER_NAME: fastapi-server

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_PEM_KEY }}
          port: ${{ env.EC2_PORT }}
          script: | # 실행할 스크립트
            cd /workspace
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_IMAGE_URL }}
            docker pull ${{ env.ECR_IMAGE_URL }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }} & echo "Docker Image Pull Succeed"
            echo "Writing .env file"
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env
            docker stop ${{ env.API_SERVER_NAME }} || true